export enum ExecutionEventType {
	AI_FUNCTION_START = "AI_FUNCTION_START",
	AI_FUNCTION_END = "AI_FUNCTION_END",
	INPUT_VALIDATION_START = "INPUT_VALIDATION_START",
	INPUT_VALIDATION_END = "INPUT_VALIDATION_END",
	INPUT_VALIDATION_ERROR = "INPUT_VALIDATION_ERROR",
	PROMPT_COMPILATION_START = "PROMPT_COMPILATION_START",
	PROMPT_COMPILATION_END = "PROMPT_COMPILATION_END",
	PROMPT_COMPILATION_ERROR = "PROMPT_COMPILATION_ERROR",
	LLM_START = "LLM_START",
	LLM_END = "LLM_END",
	LLM_ERROR = "LLM_ERROR",
	RETRY_ATTEMPT = "RETRY_ATTEMPT",
	OUTPUT_PARSING_START = "OUTPUT_PARSING_START",
	OUTPUT_PARSING_END = "OUTPUT_PARSING_END",
	OUTPUT_PARSING_ERROR = "OUTPUT_PARSING_ERROR",
	OUTPUT_VALIDATION_START = "OUTPUT_VALIDATION_START",
	OUTPUT_VALIDATION_END = "OUTPUT_VALIDATION_END",
	OUTPUT_VALIDATION_ERROR = "OUTPUT_VALIDATION_ERROR",
}

export interface ExecutionEvent {
	type: ExecutionEventType;
	timestamp: number;
	functionId?: string;
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	data: any;
}
